### ISSUE TITLE
Error while running on a test file

### ISSUE THREAD

**Issue by Natallia-Bahlai** [Yakonick/HTR_ru#2]
Got this error when trying test file (however demo1 file works)
`Segmentation stage...
Traceback (most recent call last):
  File "C:\Users\natal\Downloads\HTR_ru-main\HTR_ru-main\model\htr.py", line 152, in <module>
    model.translate(opt.input,
  File "C:\Users\natal\Downloads\HTR_ru-main\HTR_ru-main\model\htr.py", line 103, in translate
    lines_segmentation(input_path)
  File "C:\Users\natal\Downloads\HTR_ru-main\HTR_ru-main\model\segmentation.py", line 191, in lines_segmentation
    binary_image[cluster_of_interest[0]:cluster_of_interest[len(cluster_of_interest) - 1], :][:,
IndexError: index 0 is out of bounds for axis 0 with size 0`

**Comment by Sanechka-bebrik** [comment]
тоже самое. решили уже?
